apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: ${MASTER_IP}
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: Always
  imagePullSerial: false
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
clusterName: kubernetes
imageRepository: shengqipku # custom repo
kubernetesVersion: v1.31.0-kubedirect # custom tag
certificatesDir: /etc/kubernetes/pki
apiServer:
  extraArgs:
  - name: max-mutating-requests-inflight
    value: "200000"
  - name: max-requests-inflight
    value: "200000"
  - name: v
    value: "0"
scheduler:
  extraArgs:
  - name: v
    value: "2"
controllerManager:
  extraArgs:
  - name: concurrent-deployment-syncs
    value: "100"
  - name: concurrent-endpoint-syncs
    value: "50"
  - name: concurrent-replicaset-syncs
    value: "100"
  - name: concurrent-service-endpoint-syncs
    value: "50"
  - name: endpoint-updates-batch-period
    value: 50ms
  - name: endpointslice-updates-batch-period
    value: 50ms
  - name: feature-gates
    value: TopologyAwareHints=false
  - name: v
    value: "1"
dns:
  imageRepository: registry.k8s.io
  imageTag: v1.11.1
etcd:
  local:
    imageRepository: registry.k8s.io
    imageTag: 3.5.12-0
    dataDir: /var/lib/etcd
    extraArgs:
    - name: auto-compaction-mode
      value: periodic
    - name: auto-compaction-retention
      value: 15m
    - name: quota-backend-bytes
      value: "4294967296" # 4Gi
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16 # max 256 nodes
  serviceSubnet: 10.96.0.0/12
proxy: {}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  qps: 200
  burst: 400
  contentType: ""
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
clusterCIDR: ""
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocal:
  bridgeInterface: ""
  interfaceNamePrefix: ""
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  localhostNodePorts: null
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 50ms
  syncPeriod: 5m
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 5m
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
metricsBindAddress: ""
mode: "" # default: iptables
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
winkernel:
  enableDSR: false
  forwardHealthCheckVip: false
  networkName: ""
  rootHnsEndpointName: ""
  sourceVip: ""
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
  - 10.96.0.10
clusterDomain: cluster.local
# containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 2
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
resolvConf: /run/systemd/resolve/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
featureGates:
  EventedPLEG: true
  SidecarContainers: false
kubeAPIQPS: 200
kubeAPIBurst: 400
serializeImagePulls: false