apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  imagePullPolicy: Always
  # criSocket: unix:///var/run/containerd/containerd.sock
  # kubeletExtraArgs:
  #   feature-gates: "EventedPLEG=true"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: kubernetes
imageRepository: shengqipku # custom repo
kubernetesVersion: v1.31.0-kubedirect # custom tag
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    max-requests-inflight: "200000"
    max-mutating-requests-inflight: "200000"
    v: "1"
controllerManager:
  extraArgs:
    # kube-api-qps:
    # kube-api-burst:
    feature-gates: "TopologyAwareHints=false"
    concurrent-deployment-syncs: "100"
    concurrent-replicaset-syncs: "100"
    concurrent-endpoint-syncs: "50"
    concurrent-service-endpoint-syncs: "50"
    endpoint-updates-batch-period: "50ms"
    endpointslice-updates-batch-period: "50ms"
    v: "1"
scheduler:
  extraArgs:
    # kube-api-qps:
    # kube-api-burst:
    v: "1"
dns:
  imageRepository: registry.k8s.io
  imageTag: "v1.11.1"
etcd:
  local:
    imageRepository: registry.k8s.io
    imageTag: "3.5.12-0"
    dataDir: /var/lib/etcd
    extraArgs:
      quota-backend-bytes: "4294967296" # 4Gi
      auto-compaction-retention: "15m"
      auto-compaction-mode: "periodic"
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: "10.244.0.0/16"  # max 256 nodes
certificatesDir: /etc/kubernetes/pki
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  qps: 200
  burst: 400
  contentType: ""
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
clusterCIDR: ""
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocal:
  bridgeInterface: ""
  interfaceNamePrefix: ""
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  localhostNodePorts: null
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 50ms
  syncPeriod: 1m
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 1m
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
metricsBindAddress: ""
mode: "" # default: iptables
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
winkernel:
  enableDSR: false
  forwardHealthCheckVip: false
  networkName: ""
  rootHnsEndpointName: ""
  sourceVip: ""
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
  - 10.96.0.10
clusterDomain: cluster.local
# containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: "1"
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
resolvConf: /run/systemd/resolve/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
featureGates:
  EventedPLEG: true
kubeAPIQPS: 200
kubeAPIBurst: 400
serializeImagePulls: false
