apiVersion: v1
kind: Node
metadata:
  name: ${NODENAME}
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    type: kwok
    kubernetes.io/hostname: ${NODENAME}
    # mark as fake so daemonset with high toleration like kube-proxy won't get scheduled
    beta.kubernetes.io/arch: fake-amd64
    beta.kubernetes.io/os: fake-linux
    kubernetes.io/arch: fake-amd64
    kubernetes.io/os: fake-linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
     # Set empty addr label to avoid dialing until we populate it
    kubedirect/kubelet-service-addr: ""
spec:
  taints: # Avoid scheduling real pods to fake Node
  - effect: NoSchedule
    key: kwok.x-k8s.io/node
    value: fake
status:
  allocatable:
    cpu: 48
    memory: 128Gi
    pods: 110
  capacity:
    cpu: 48
    memory: 128Gi
    pods: 110
  nodeInfo:
    architecture: fake-amd64
    operatingSystem: fake-linux
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    osImage: ""
    systemUUID: ""
  phase: Running